
[server]
hostname = "lists.python.org"
allowed-ip = { "172.168.123.1", "172.168.123.10" }

[session.ehlo]
require = true
reject-non-fqdn = [
  { if = "remote_ip == '172.168.123.1'", then = false },
  { if = "remote_ip == '172.168.123.10'", then = false },
  { if = "local_port == 25", then = true },
  { else = false }
]

[session.hook."mailman"]
enable = "true"
url = "http://mailman-core:8001/3.1/plugins/mailman_stalwart/hook"
stages = ["rcpt", "data"]
allow-invalid-certs = false

[session.hook."mailman".options]
tempfail-on-error = true
max-response-size = 52428800

[session.hook."mailman".auth]
username = "restadmin"
secret = "restpass"

[authentication.fallback-admin]
user = "admin"
secret = "$6$PjzSrjsHyTaxjaJ3$AwloEYHf.3gpHH.pymwKesm0Z/biSOUm3GG2.dZ3rnpnf5UsPjTCDWmr0y2FstbfKKXTxxwzOOySGw.eEwg8I."  # "password"

[remote."mailman"]
address = "mailman-core"
port = 8024
protocol = "lmtp"
[remote."mailman".tls]
implicit = false
allow-invalid-certs = false

[queue.outbound]
next-hop = [
  # { if = "rcpt_domain = 'x.python.org'", then = "'mailman'" },  # These are created automatically by integration when domains are added
  { if = "is_local_domain('', rcpt_domain)", then = "'local'" }, 
  { else = false }
]

[queue.outbound.tls]
starttls = "optional"

# These are all boiler plate
[directory.internal]
store = "rocksdb"
type = "internal"

[server.listener.http]
bind = "[::]:8080"
protocol = "http"

[server.listener.https]
bind = "[::]:443"
protocol = "http"

[server.listener.https.tls]
implicit = true

[server.listener.imap]
bind = "[::]:143"
protocol = "imap"

[server.listener.imaptls]
bind = "[::]:993"
protocol = "imap"

[server.listener.imaptls.tls]
implicit = true

[server.listener.pop3]
bind = "[::]:110"
protocol = "pop3"

[server.listener.pop3s]
bind = "[::]:995"
protocol = "pop3"

[server.listener.pop3s.tls]
implicit = true

[server.listener.sieve]
bind = "[::]:4190"
protocol = "managesieve"

[server.listener.smtp]
bind = "[::]:25"
protocol = "smtp"

[server.listener.submission]
bind = "[::]:587"
protocol = "smtp"

[server.listener.submissions]
bind = "[::]:465"
protocol = "smtp"

[server.listener.submissions.tls]
implicit = true

[storage]
blob = "rocksdb"
data = "rocksdb"
directory = "internal"
fts = "rocksdb"
lookup = "rocksdb"

[store.rocksdb]
compression = "lz4"
path = "%{env:STALWART_PATH}%/data"
type = "rocksdb"

[tracer.stdout]
ansi = false
enable = true
level = "debug"
lossy = false
type = "stdout"
